version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn -B package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - mv ./target/mybloombud-0.0.1-SNAPSHOT.jar mybloombud-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - mybloombud-0.0.1-SNAPSHOT.jar